name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://jenkins.zeus.panteon.games/"
        user: ${{ secrets.JenkinsUsername }}
        token: ${{ secrets.JenkinsAPIToken }}
        job: "Midcore-KoPDevelopment-Android"
