# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: jenkins-CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger jenkins job
      uses: joshlk/jenkins-githubaction@master
      with:
        # Jenkins URL including http/https protocol
        url: https://jenkins.zeus.panteon.games/
        # Jenkins job name to build
        job_name: DevOps-ANRTest-IOS
        # Jenkins username
        username: ${{ secrets.JenkinsUsername }}
        # Jenkins API token
        api_token: ${{ secrets.JenkinsAPIToken }}
        # Should the runner wait for the build to finish and provide ok status
        wait: True
        # Timeout in seconds for build to complete
        timeout: 60
        # How frequently in seconds to query Jenkins for build status
        interval: 10
        parameters: '{"CleanBuild":true,"DebugMode":true,"LogMode":true,"LocalMode":true,"ClearLibrary":false,"Development":"None","Assets/Game/Textures/icon.png":"(No file was uploaded)"}'
